
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrongPassword123!
    ports:
      - "1433:1433"
    networks:
      - app-network

  api:
    build:
      context: ./Backend
      dockerfile: ./GestionInventarioLibros/Dockerfile
    container_name: inventory-api
    ports:
      - "8081:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=GestionInventarioLibrosDb;User Id=sa;Password=YourStrongPassword123!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
